Repository cloudmobility/charts, pull requests merged in 2021-07, with the labels that each got.

#5 feat(grafana): add cloudmobility grafana tailored chart
  README.md
  charts/grafana/.gitignore
  charts/grafana/.helmignore
  charts/grafana/Chart.lock
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/grafana/icons/grafana-240x240.png
  charts/grafana/templates/NOTES.txt
  charts/grafana/values.yaml
Labels: enhancement, new chart

#7 chore(github): add github templates for issues, feature request and pull requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE
Labels: documentation, enhancement

#9 fix(charts): chart icons
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE
  charts/grafana/Chart.yaml
  charts/hello/Chart.yaml
Labels: bug

#13 feat(grafana): add automatic hostname to grafana tailored chart
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/grafana/templates/NOTES.txt
  charts/grafana/templates/ingress.yaml
  charts/grafana/values.cloudmobility.yaml
  charts/grafana/values.yaml
Labels: enhancement

#11 chore(github): add contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#15 feat(hello): add automatic hostname generation
  charts/hello/.gitignore
  charts/hello/.helmignore
  charts/hello/Chart.yaml
  charts/hello/README.md
  charts/hello/templates/NOTES.txt
  charts/hello/templates/deployment.yaml
  charts/hello/templates/ingress.yaml
  charts/hello/values.cloudmobility.yaml
  charts/hello/values.yaml
Labels: documentation, enhancement

#17 fix(hello): disable auto scaling by default
  charts/hello/Chart.yaml
  charts/hello/README.md
  charts/hello/values.yaml
Labels: bug
